/*** Copyright (C) 2019-2021 ZaidaTek and Andreas Riebesehl
**** This work is licensed under: Creative Commons Attribution-NoDerivatives 4.0 International Public License
**** For full license text, please visit: https://creativecommons.org/licenses/by-nd/4.0/legalcode
***/
#ifndef ZS_TEXT_H_INCLUDED
#define ZS_TEXT_H_INCLUDED

#define ZSCOPE_TEXT_LANG_EN 0
#define ZSCOPE_TEXT_LANG_DE 1
#define ZSCOPE_DEFAULT_TEXT_LANG ZSCOPE_TEXT_LANG_EN

#define ZSTX_VERSION 0
#define ZSTX_TITLE 1
#define ZSTX_WINDOW 2
#define ZSTX_MN_DEVICE 3
#define ZSTX_MN_HELP 4
#define ZSTX_MN_CREDITS 5
#define ZSTX_MN_SETTINGS 6
#define ZSTX_MN_EXIT 7
#define ZSTX_MN_CONNECT 8
#define ZSTX_MN_DISCONNECT 9
#define ZSTX_MN_LBL_ADDRESS 10
#define ZSTX_MN_LBL_SPEED 11
#define ZSTX_MN_LBL_SPEED_R 12
#define ZSTX_MN_LBL_CHANNEL 13
#define ZSTX_MN_LBL_CHANNEL_L 14
#define ZSTX_MN_LBL_CHANNEL_R 15
#define ZSTX_MN_HELP_DESC 16
#define ZSTX_MN_CREDITS_DESC 17
#define ZSTX_MN_SET_RENDER_SYS 18
#define ZSTX_MN_SET_RENDER_GL 19
#define ZSTX_MN_SET_LANG_EN 20
#define ZSTX_MN_SET_LANG_DE 21
#define ZSTX_HD_MENU 22
#define ZSTX_HD_CAPTURE_OFF 23
#define ZSTX_HD_CAPTURE_ON 24
#define ZSTX_HD_RECORD_OFF 25
#define ZSTX_HD_RECORD_ON 26
#define ZSTX_HD_SELECT_DIA 27
#define ZSTX_HD_SELECT_TRI 28
#define ZSTX_HD_SELECT_MES 29
#define ZSTX_HD_SELECT_CUR 30
#define ZSTX_HD_DIA_TYPE_SCAN 31
#define ZSTX_HD_DIA_TYPE_FIXED 32
#define ZSTX_HD_DIA_RESET 33
#define ZSTX_HD_DIA_BMP 34
#define ZSTX_HD_DIA_PNG 35
#define ZSTX_HD_TRI_MODE_NONE 36
#define ZSTX_HD_TRI_MODE_CONT 37
#define ZSTX_HD_TRI_MODE_SINGLE 38
#define ZSTX_HD_TRI_TYPE_RISING 39
#define ZSTX_HD_TRI_TYPE_FALLING 40
#define ZSTX_HD_TRI_CH_1 41
#define ZSTX_HD_TRI_CH_2 42
#define ZSTX_HD_TRI_CH_3 43
#define ZSTX_HD_TRI_CH_4 44
#define ZSTX_HD_TRI_CH_5 45
#define ZSTX_HD_TRI_CH_6 46
#define ZSTX_HD_TRI_CH_7 47
#define ZSTX_HD_TRI_CH_8 48
#define ZSTX_HD_TRI_LBL_HOLDOFF 49
#define ZSTX_HD_TRI_LBL_HOLDOFF_R 50
#define ZSTX_HD_MES_UNIT_RAW 51
#define ZSTX_HD_MES_UNIT_PHY 52
#define ZSTX_HD_CUR_TYPE_NONE 53
#define ZSTX_HD_CUR_TYPE_TIME 54
#define ZSTX_HD_CUR_TYPE_VOLT 55
#define ZSTX_HD_CUR_TARGET_1 56
#define ZSTX_HD_CUR_TARGET_2 57

#define ZSTX_TOTAL 58

#endif //ZS_TEXT_H_INCLUDED
